#!/bin/bash

# read .env file
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
else
    echo ".env file not found!"
    exit 1
fi

echo "Test backup s3"
echo "Test env:"

env

echo "Check the RSYNC_DST=$RSYNC_DST and SFTP_DST=$SFTP_DST variables"
