#!/bin/bash

# read .env file
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
else
    echo ".env file not found!"
    exit 1
fi

echo "Test backup s3"
echo "Test env:"

env

echo "Check the RSYNC_DST=$RSYNC_DST and SFTP_DST=$SFTP_DST variables"

if [ -z "$RSYNC_DST" ]; then
    echo "RSYNC_DST is not set in .env file!"
    exit 1
fi

SRC=/var/discourse/shared/standalone/backups/
DST=$RSYNC_DST

echo "DRY RUN: rsync -avz $SRC $DST"
#rsync -avz $SRC $DST
